app:
 name: "web_app"
 mode: "dev"
 port: 8081
start_time: "2020-07-01"

log:
 level: "debug"
 filename: "web_app.log"
 max_size: 200
 max_age: 30
 max_backups: 7

mysql:
 host: "0.0.0.0"
 port: 3306
 user: "root"
 password: "123456"
 dbname: "mysql"
 max_open_conns: 200
 max_idle_conns: 50

redis:
 host: "0.0.0.0"
 port: 6379
 db: 0
 password: ""
 poolsize: 100
